// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkpa8N35c6ofybmp1crlhsORHX4iIrKK8',
    appId: '1:1078014093779:web:fb6c17782787827738e726',
    messagingSenderId: '1078014093779',
    projectId: 'smartwaalo',
    authDomain: 'smartwaalo.firebaseapp.com',
    storageBucket: 'smartwaalo.appspot.com',
    measurementId: 'G-37V0V4DEL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtTR9ttaWL31LB46Ray4srCI1JAXhzn-s',
    appId: '1:1078014093779:android:dbc045ede2f4b7b738e726',
    messagingSenderId: '1078014093779',
    projectId: 'smartwaalo',
    storageBucket: 'smartwaalo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGYvEowNm58-e8HiB23bRmMNM6fGvYJeM',
    appId: '1:1078014093779:ios:41fa6584b5f5fb1238e726',
    messagingSenderId: '1078014093779',
    projectId: 'smartwaalo',
    storageBucket: 'smartwaalo.appspot.com',
    iosBundleId: 'com.example.parkingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGYvEowNm58-e8HiB23bRmMNM6fGvYJeM',
    appId: '1:1078014093779:ios:00134e491d7ae76838e726',
    messagingSenderId: '1078014093779',
    projectId: 'smartwaalo',
    storageBucket: 'smartwaalo.appspot.com',
    iosBundleId: 'com.example.parkingApp.RunnerTests',
  );
}
